/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 21-Mar-2024 15:44:47
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 250
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include <stdint.h>
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2021a.app/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define BPL 200
int16_t BP[200] = {
    -9275,   5058,   2877,   1015,   -302,   -994,  -1113,   -819,   -321,
      172,    508,    608,    486,    214,    -98,   -347,   -459,   -416,
     -245,    -15,    197,    321,    329,    220,     45,   -149,   -277,
     -330,   -268,   -126,     35,    184,    262,    243,    136,    -12,
     -161,   -263,   -285,   -216,    -82,     73,    193,    245,    211,
      103,    -48,   -189,   -278,   -278,   -193,    -46,    109,    226,
      264,    205,     76,    -92,   -239,   -316,   -297,   -184,     -9,
      170,    291,    312,    222,     45,   -162,   -331,   -401,   -346,
     -176,     58,    282,    419,    415,    260,     -4,   -296,   -521,
     -592,   -471,   -176,    212,    568,    765,    711,    384,   -150,
     -745,  -1209,  -1347,  -1016,   -175,   1103,   2627,   4133,   5338,
     6006,   6006,   5338,   4133,   2627,   1103,   -175,  -1016,  -1347,
    -1209,   -745,   -150,    384,    711,    765,    568,    212,   -176,
     -471,   -592,   -521,   -296,     -4,    260,    415,    419,    282,
       58,   -176,   -346,   -401,   -331,   -162,     45,    222,    312,
      291,    170,     -9,   -184,   -297,   -316,   -239,    -92,     76,
      205,    264,    226,    109,    -46,   -193,   -278,   -278,   -189,
      -48,    103,    211,    245,    193,     73,    -82,   -216,   -285,
     -263,   -161,    -12,    136,    243,    262,    184,     35,   -126,
     -268,   -330,   -277,   -149,     45,    220,    329,    321,    197,
      -15,   -245,   -416,   -459,   -347,    -98,    214,    486,    608,
      508,    172,   -321,   -819,  -1113,   -994,   -302,   1015,   2877,
     5058,  -9275
};
