/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 21-Mar-2024 16:16:40
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 200
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include <stdint.h>
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2021a.app/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define LPL 200
int16_t LP[200] = {
     1133,     33,      0,    -44,    -84,   -107,   -104,    -75,    -29,
       20,     54,     63,     42,     -3,    -56,   -101,   -122,   -110,
      -70,    -11,     45,     80,     82,     48,    -10,    -75,   -124,
     -141,   -117,    -61,     12,     76,    110,    102,     52,    -25,
     -102,   -155,   -164,   -124,    -47,     43,    116,    147,    123,
       51,    -49,   -142,   -197,   -194,   -131,    -26,     87,    171,
      195,    148,     43,    -88,   -201,   -258,   -236,   -137,      9,
      156,    253,    264,    180,     24,   -156,   -301,   -358,   -301,
     -142,     74,    277,    396,    384,    232,    -20,   -296,   -502,
     -561,   -435,   -145,    230,    570,    753,    691,    364,   -164,
     -749,  -1200,  -1326,   -989,   -146,   1125,   2638,   4132,   5327,
     5990,   5990,   5327,   4132,   2638,   1125,   -146,   -989,  -1326,
    -1200,   -749,   -164,    364,    691,    753,    570,    230,   -145,
     -435,   -561,   -502,   -296,    -20,    232,    384,    396,    277,
       74,   -142,   -301,   -358,   -301,   -156,     24,    180,    264,
      253,    156,      9,   -137,   -236,   -258,   -201,    -88,     43,
      148,    195,    171,     87,    -26,   -131,   -194,   -197,   -142,
      -49,     51,    123,    147,    116,     43,    -47,   -124,   -164,
     -155,   -102,    -25,     52,    102,    110,     76,     12,    -61,
     -117,   -141,   -124,    -75,    -10,     48,     82,     80,     45,
      -11,    -70,   -110,   -122,   -101,    -56,     -3,     42,     63,
       54,     20,    -29,    -75,   -104,   -107,    -84,    -44,      0,
       33,   1133
};
